server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://backend:3000/;
    proxy_set_header Host $host;
  }
  location /ai/ {
    proxy_pass http://ai:8000;
    proxy_read_timeout 60s;
  }
  location / {
    try_files $uri /index.html;
  }
}
